#spring.application.name=ServiceScore
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
#    username: your-email@gmail.com
    username: trankimhieu1008@gmail.com
    password: lldq uzsm agwe vqwi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    #TODO: Private this ...
    ##
    url: jdbc:postgresql://dpg-d195t0vdiees73ai0lu0-a.oregon-postgres.render.com/servicescore_db
    username: root #user postgres
    password: gwlYGTRkLD8efzDB5IL5yKAAIgzxKrzq #Mat khau
#
#    url: jdbc:postgresql://localhost:5432/servicescore_db #ten database
#    username: postgres
#    password: trankimhieu123 #Mat khau

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false  # Phải đặt là false nếu dùng "*"
    resources:
      static-locations: file:uploads/
api:
  prefix: api/v1

jwt:
  expiration: 2592000   #30 days = 30 * 24 * 60 * 60
  secretKey: quJH8fRdfN2X3GZyTlKmYPQWzrCd5VABeMJLOaXsUc0=

supabase:
  url: https://axcowrrqdyrtpguxnqun.supabase.co
  apiKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4Y293cnJxZHlydHBndXhucXVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Njc3MzU2MSwiZXhwIjoyMDYyMzQ5NTYxfQ.UxBwx75prS0W45lD1G5mbPd-w4TBAyAdzHpSDX8PGkw
  bucket: external-event-proofs


